### ISSUE TITLE
which MIDIUSB library needed?

### ISSUE THREAD

**Issue by twisted-electrons** [Levi--G/USBLibrarySTM32#3]
Hello! 
I'm trying to set up MIDIUSB using the following official core:

[env:genericSTM32F103CB]
platform = ststm32
board = genericSTM32F103CB
framework = arduino

However MIDIUSB.h is needed. Can you please share which version will work with your library?
I tried adding MIDIUSB by Gary Grewal buy it won't compile:
#error MIDIUSB can only be used with an USB MCU.

I'd be grateful for your guidance!
Thanks for making this possible, very excited to enjoy the USB midi with the official core!

**Comment by twisted-electrons** [comment]
Sorry found it in your example!

**Comment by Levi--G** [comment]
Glad to see you found it! Let me know if you encounter issues or need help :)
